export const posts = [
  {
    id: 1,
    name: 'Nike',
    model: 'Shock',
    description: 'lorem ipsum dolor sit amet',
    countInStock: 21,
    year: 2016,
    price: 199,
  },
  {
    id: 2,
    name: 'Adidas',
    model: 'Wave',
    description: 'lorem ipsum dolor sit amet',
    countInStock: 29,
    year: 2020,
    price: 249,
  },
  {
    id: 3,
    name: 'New Balance',
    model: 'One',
    description: 'lorem ipsum dolor sit amet',
    countInStock: 19,
    year: 2021,
    price: 129,
  },
  {
    id: 4,
    name: 'Puma',
    model: 'Trace',
    description: 'lorem ipsum dolor sit amet',
    countInStock: 19,
    year: 2021,
    price: 229,
  },
]
